###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "super8"
    name: "Super 8"
    type: software
    subtypes:
      - web
      - wordpress-plugin
      - browser-extension
      - Chrome-extension
      - Firefox-extension
    version: "0.0.13"
    description: "{{package.description}}"
    homepage: "{{package.homepage}}"
    repo: "https://github.com/pigeonposse/super8"
    logo: "https://raw.githubusercontent.com/pigeonposse/super8/main/docs/images/logo-short.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/super8/main/docs/images/banner.png"
    status: "active"

###############################################################################
