###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "super8"
    name: "Super 8"
    type:
      - web
      - wpa
      - wp-plugin
      - browser-extension
      - chrome-extension
      - firefox-extension
      - edge-extension
      - safari-extension
      - chromium-extension
      - brave-extension
      - opera-extension
      - operagx-extension
      - yandex-extension
    version: "0.0.13"
    description: "{{package.description}}"
    homepage: "{{package.homepage}}"
    package: "https://www.npmjs.com/package/@s-8/core"
    docs: "{{package.extra.docsUrl}}"
    repo: "https://github.com/pigeonposse/super8"
    logo: "https://raw.githubusercontent.com/pigeonposse/super8/main/docs/images/logo-short.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/super8/main/docs/images/banner.png"
    status: "active"
    download: 
      - name: "Chrome store"
        url:  "https://chromewebstore.google.com/detail/super8/aejkinmllndkgoodkfbhfkffnebmibkd"
      - name: "chrome manifest v2"
        url: "https://github.com/pigeonposse/super8/releases/latest/download/super8-chrome-mv2.zip"

###############################################################################
