version: '3'
services:
  super8-dev-env:
    build: .
    container_name: super8-dev-env
    restart: always
    volumes:
          - ..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"