[package]
# Some of this are used in build process of tauri
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
name = "super8"
version = "0.2.2"
description = "🎬🎨🧩 Add styles to web video like iFrames, YouTube & Vimeo videos, Netflix, Amazon etc"
authors = ["angelo <angelo@pigeonposse.com>"]
# license = "GPL-3.0"
license-file = "../../../LICENSE"
repository = "https://github.com/pigeonposse/super8"
edition = "2021"
homepage = "https://super8.pigeonposse.com/"
documentation = "https://docs.super8.pigeonposse.com/"
readme = "../../../README.md"
keywords = [
    "super-8",
    "youtube",
    "styles",
    "video",
    "iframe",
    "browser-extension",
    "chrome-extension",
    "web"
]

[lib]
name = "super8_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.13", features = [] }

[dependencies]
serde_json = "1.0"
tauri = { version = "2.0.0-beta.13", features = ["macos-private-api"] }
tauri-plugin-shell = "2.0.0-beta.9"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2.0.0-beta.9"
# tauri-plugin-window = "2.0.0-alpha"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
