[package]
name = "super8"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = "GPL-3.0"
repository = "https://github.com/pigeonposse/super8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "super8_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.2", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta.2", features = ["macos-private-api"] }
tauri-plugin-shell = "2.0.0-beta.2"
serde_json = "1.0"
[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2.0.0-beta.2"
# tauri-plugin-window = "2.0.0-alpha"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
