###############################################################################
# DEPLOY WEBS TO CLOUDFLARE
###############################################################################

name: Deploy webs


###############################################################################
# ON
###############################################################################

on:
  
    push:
      branches:
        - main
      paths:
        - 'docs/**'
        - 'packages/docs/package.json'


###############################################################################
# JOBS
###############################################################################

jobs:

    deploy:

        name: Deploy SUPER8 webs
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write

        #######################################################################
        # STEPS
        #######################################################################

        steps:

            #########################################################################
            # INIT & BUILD PKG
            #########################################################################
            
            - name: 🛎 Checkout
              uses: actions/checkout@v3


            #########################################################################
            # BUILD PKG
            #########################################################################

            - name: 🏗 Install pnpm
              uses: pnpm/action-setup@v2
              id: pnpm-install

            - name: 👨🏻‍💻 Install pkg dependencies
              run: |
                pnpm install --no-frozen-lockfile
                pnpm build:docs
            
            ###################################################################
            # INIT & BUILD PKG
            ###################################################################

            - name: 🌥 Deploy DOCS in cloudflare pages
              uses: cloudflare/pages-action@v1
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                branch: main
                projectName: "super8-docs"
                directory: 'packages/docs/dist'
                wranglerVersion: '3'