###############################################################################
# PUBLISH CORE IN NPM 
###############################################################################

name: Deploy webs


###############################################################################
# ON
###############################################################################

on:
  
    push:
        branches:
            - main
        paths:
            - 'packages/_core/package.json'
            - 'packages/_core-react/package.json'


###############################################################################
# JOBS
###############################################################################

jobs:

    build:
  
        name: Publish core
        runs-on: ubuntu-latest

        ###########################################################################
        # STEPS
        ###########################################################################

        steps:

            #########################################################################
            # INIT & BUILD PKG
            #########################################################################
            
            - name: 🛎 Checkout
              uses: actions/checkout@v3


            #########################################################################
            # BUILD PKG
            #########################################################################

            - name: 🏗 Install pnpm
              uses: pnpm/action-setup@v2
              id: pnpm-install

            - name: 👨🏻‍💻 Install pkg dependencies
              run: |
                pnpm install --no-frozen-lockfile

            - name: 🌐 Install Playwright Browsers
              run: npx playwright install --with-deps

            ###################################################################
            # BUILD
            ###################################################################
            
            - name: 🏗 Build package
              run:  pnpm build:core

            ###################################################################
            # PUBLISH
            ###################################################################

            - name: Publish to NPM
              id: changesets
              uses: changesets/action@v1
              # with:
              #   publish: pnpm release:core
              env:
                GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  